version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=emd
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
  api:
    container_name: api
    image: bollywoodle-be-img
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    restart: always
    dns:
      - 8.8.8.8

volumes:
  mysqldb: