version: '3.7'

services:
  app-server:
    container_name: app-server
    image: bollywoodle-be-img
    build:
      context: bollywoodle-be
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    dns:
      - 8.8.8.8
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: bollywoodle-fe
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

networks:
  backend:
  frontend: